### ISSUE TITLE
Regarding the Walker2d-Randparams Environment 

### ISSUE THREAD

**Issue by jonathanbrady88** [lmzintgraf/varibad#13]
Thank you for your inspirational great work and open sourcing the code. I have a question regarding the walker random environment. The walker can not walk when the reward is 800, this is the case for all the algorithms that use this environment. When doing a comparative analysis are we supposed to only compare the reward or is the reward scaled for this environment?

Have you observed a walking behavior when using the algorithms that use this environment?

**Comment by lmzintgraf** [comment]
Thanks for the encouraging words! :) 

> The walker can not walk when the reward is 800 (...) Have you observed walking behaviour when using the algorithms that use this environment?

I haven't actually looked at what the trained varibad walker does. Do you know what reward threshold requires walking? My experts get close to ~1300 (on average, one expert trained per task), my multi-task policy gets to slightly above 1000, and varibad to slightly below 1000. (These numbers are from our [JMLR paper](https://www.jmlr.org/papers/v22/21-0657.html))

> When doing a comparative analysis are we supposed to only compare the reward

Yes I think we should compare algorithms primarily in terms of expected return, since that is the objective they ought to be optimising. Although a qualitative comparison of learned behaviour can also be very interesting. 

> is the reward scaled for this environment?

Can you clarify this question? I'm not sure I understand it correctly. I used the rewards returned by the environment to compute the expected return that is shown on the plots. For training I may use normalised / discounted rewards / returns, but that does not show up on the eval plots.

**Comment by jonathanbrady88** [comment]
Thank you for your detailed response! 
When I rendered the walker environment to observe the walking behavior, I haven't observed a consistent walking behavior below 2000. 
In single task RL, the benchmark  results for Walker2d is 3424.95 for ppo2 and 2342.63   for trpo https://github.com/openai/baselines/blob/master/benchmarks_mujoco1M.htm .

In Mujoco Environments where state and action spaces are large like Humanoid, the rewards returned by the environment is sometimes scaled by a constant value of 0.1 (as in https://github.com/openai/baselines/ppo1/run_humanoid.py). I thought maybe a scaling in the walker-2d-rand-params environment that I may have missed might be the reason or this is a really challenging environment.

**Comment by lmzintgraf** [comment]
> When I rendered the walker environment to observe the walking behavior, I haven't observed a consistent walking behavior below 2000.

That's curious. Is that consistent across different tasks in the meta-RL benchmark (i.e. different shapes of the walker)? Or are you referring to performance in the the single-task env (which may be different so we can't directly compare them - see my next answer). 

In either case, this is good to know. I'd be curious to see what my agents are doing - will look into this if I find the time.

> In single task RL, the benchmark results for Walker2d is 3424.95 for ppo2 and 2342.63 for trpo https://github.com/openai/baselines/blob/master/benchmarks_mujoco1M.htm .

I don't think that the meta-learning benchmark and the single-task benchmark can be compared. I never looked into how they differ, I took the envs from the [PEARL repo](https://github.com/katerakelly/oyster) (though the benchmark was introduced earlier somewhere). I suspect the people who first introduced it had to make some changes to make the multi/meta-task setting work, which may include the reward structure. The task difficulty also varies across different walker tasks in the meta-RL benchmark, so they'll have different returns and this would influence the average return across tasks (and be different from the single-task avg return).

> In Mujoco Environments where state and action spaces are large like Humanoid, the rewards returned by the environment is sometimes scaled by a constant value of 0.1

Oh, gotcha. That's just a choice in the PPO training algorithm though, right? So wouldn't show up on the evaluation plot anyway. 

I don't scale the rewards with a fixed scalar, but I do normalise them for the walker env (see the [configs](https://github.com/lmzintgraf/varibad/blob/master/config/mujoco/args_walker_varibad.py#L34)), so the rewards that the PPO agent is trained with are effectively scaled. But the return plots in the paper are calculated with the raw rewards.
