### ISSUE TITLE
Is it possible to watch 'belief' variable on the MuJoCo environment?

### ISSUE THREAD

**Issue by JM-Kim-94** [lmzintgraf/varibad#16]
Hi Luisa, your VariBAD algorithm codes are well recognized, so they are very helpful for me to study meta reinforcement learning, thanks for your works! 

I have a question about the 'belief' variable in the "metalearner.py", 
I can watch how the belief variable variate on the gridworld env, by applying arguments like; 
"--pass_belief_to_policy True, --policy_belief_embedding_dim 32" in the "args_grid_varibad.py" file. 

but I have an error with mujoco environment, when I apply the same configuration like above to "args_cheetah_vel_varibad.py" to watch how the belief variable variate. 

![image](https://user-images.githubusercontent.com/78307871/213974903-890b357a-c53c-4a34-9a2b-4d73cf245f23.png)

Is it possible to check 'belief' variable on the MuJoCo environment? 

I thought that the belief variable is only watchable on the Grid world environment, and not watchable on the mujoco env, am I right?

**Comment by lmzintgraf** [comment]
Hi, thanks for your question! 

Setting `--pass_belief_to_policy True` passes the _ground-truth_ belief to the policy as an input (which is called "belief oracle" in the paper), _if_ the environment provides the ground-truth belief. I implemented this for the gridworld where the belief is easy to compute/represent. However, this is not the case for MuJoCo. If you would like to have this, you'd have to implement the ground-truth belief update in the different MuJoCo tasks. You might not be able to do this exactly, but you could for example see if you can reverse-engineer the task (let's say velocity) from the rewards received over the first few timesteps, and use that as an approximate belief. 

Hope this helps!

**Comment by JM-Kim-94** [comment]
Thanks for your detailed response! 
Best regards
