### ISSUE TITLE
About results of PEARL

### ISSUE THREAD

**Issue by yingchengyang** [lmzintgraf/varibad#21]
Thanks for open-sourcing great codes of VariBAD. As the results in the paper include the results of PEARL with one rollout (like Fig. 4 and Fig. 6), could you please provide these results for us to compare (the results provided seem only to include RL2 and VariBAD)? Thanks a lot!

**Comment by lmzintgraf** [comment]
Hi, sorry I don't have those results readily available anymore. I produced them using the official PEARL repository (https://github.com/katerakelly/oyster).
